sudo: required
language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 82.202.246.5

before_install:
- openssl aes-256-cbc -K $encrypted_7124dd760b8f_key -iv $encrypted_7124dd760b8f_iv
  -in deploy_rsa.enc -out deploy_rsa -d

before_deploy:
- npm run build
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/static root@82.202.246.5:/root/travis-files/tanks-frontend
  on:
    branch: game-dev

